[package]
name = "proto"
version = "0.1.0"
authors = ["Hector Salazar <hecsalazarf@outlook.com>"]
edition = "2018"

[dependencies]
prost = "0.6.1"
tonic = "0.3.1"

[build-dependencies]
tonic-build = "0.3.1"
